[phases.setup]
nixPkgs = ["nodejs_20", "python311", "ffmpeg"]

[phases.install]
cmds = ["python3 -m pip install streamlink", "npm install --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = ["npm run start"]